import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/navigation/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio made with Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="main-container-layout">
        <header>
          <SideBar />
        </header>
        <main className='main-content'>
          <div className="inner-content flex flex-col lg:flex-row-reverse justify-center align-center items-center lg:gap-5">
            {children}
          </div>
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
